### ISSUE TITLE
thread 'main' panicked at 'failed to retrieve cli value', src/libcore/option.rs:1038:5

### ISSUE THREAD

**Issue by digiwizkid** [Peltoche/vixi#4]
I am getting this issue while `cargo run`
`thread 'main' panicked at 'failed to retrieve cli value', src/libcore/option.rs:1038:5`

**Comment by kristianpaul** [comment]
$ vixi something.txt
failed to load the configuration: No such file or directory (os error 2)
$ touch something.txt
$ vixi something.txt
failed to load the configuration: No such file or directory (os error 2)
 
Probably related

**Comment by Peltoche** [comment]
Hi @digiwizkid , thanks for the report!

You need to specify a file at in order to start it. This error handling needs a lot of work. I will handle this asap.


Hi @kristianpaul,

Your error is due to the fact that at the moment the keyboard configuration file at `~/.config/vixi/keyboard.vim` is required to start, you can find an example inside the [here](https://github.com/Peltoche/vixi/blob/master/resources/keyboard.toml).

That said, the binary already contains the default configurations so the configuration shouldn't be required. I will fix this ASAP.

**Comment by axionbuster** [comment]
try

```
$ ./vixi file=abc.txt
```

If you use **`file=`**, it will be OK.

See source code in main.rs, master, lines 83-7:
```
    let matches = cli::build().get_matches();

    let file_path = matches
        .value_of("file")
        .expect("failed to retrieve cli value");
```
